data:
  train_csv: "data/train.csv"
  train_audio_dir: "data/audio_train/train"
  test_audio_dir: "data/audio_test/test"
  noise_dir: "data/audio_train/train" 
  submission_csv: "data/submission.csv"
  test_size: 800

audio:
  sample_rate: 16000

model:
  num_classes: 41
  lr: 0.00001
  weight_decay: 0.1
  milestones: [2, 4]

training:
  batch_size: 4
  gradient_accumulation_steps: 4
  max_epochs: 15
  patience: 5
  random_state: 42
  num_workers: 4

augmentation:
  use_specaug: False
  max_proportion: 0.3
  mixin_prob: 0.5
  snr_db: 15
